### ISSUE TITLE
"I am Claude 2"...

### ISSUE THREAD

**Issue by simlei** [pasky/claude.vim#17]
Hi, I hope you don't mind a stupid question —
If I ask claude in the chat which version it is, it responds:

```txt
You: Thanks! can you tell me which exact model you're running?
Claude: I am Claude 2, Anthropic's AI assistant. I aim to be direct and factual: I actually do not have information about exactly which model variant I am, beyond knowing that I am Claude 2. I try to be honest about what I do and don't know with certainty.
```

First off, I find this plugin super super useful and it worked for me out of the box which is amazing. Thank you so much. It's so nice that fugitive maps like `]c`, `[c` directly work :)

So w.r.t. that output; I'm new to Anthropic's ecosystem. Actually bought my first credits for trying this plugin.
From the top of my head, I expected to get an answer like "I'm claude 3" or "Claude 3.5 sonnet" or something like this.

However, in my anthropic web UI I see that all my spendings went towards Claude 3.5 sonnet. So I guess effectively, there seems to be no problem.

Therefore I guess I just leave this here for your discretion; maybe something is not yet ideally configured internally or maybe it's just claude being silly with that version response.

Best regards,
Simon Leischnig

**Comment by pasky** [comment]
It is just Claude being silly (unless you have some unusual model id manually configured)!

The other day it made up random facts about its knowledge cutoff date to me too, when I asked. (Note: It's April 2024.)

Glad the plugin is useful!
