### ISSUE TITLE
How to prune history?

### ISSUE THREAD

**Issue by voidzero** [pasky/claude.vim#19]
Hi, i'm new to this plugin and the readme, at the very bottom, states:

> Prune your chat history regularly.

How do we do this?

**Comment by pasky** [comment]
Simply edit the Claude window content, delete lines irrelevant to the chat. (You don't need to be super careful about it, it's just an advice to help keep the context size in check and help you save costs.)

What gets sent to Claude exactly corresponds to the content of this window.

**Comment by voidzero** [comment]
Ah! Got it thanks
