### ISSUE TITLE
Is there any way to end a chat without quiting the Neovim?

### ISSUE THREAD

**Issue by csy19960309** [pasky/claude.vim#2]
Simply closing the chat buffer does not help.

**Comment by csy19960309** [comment]
Deleting the content of chat buffer works. Closing this issue.

**Comment by pasky** [comment]
Just to clarify further:
* You can `:bd` to close window and delete the buffer - `<Leader>cc` will then create a new one.
* You can also just randomly edit the chat history. Either wipe it out, or delete some of the old interactions (`dd` on a closed fold will delete the whole fold btw), or anything else. There is no "hidden state" beyond what's in the buffer, each followup interaction is based on the chat buffer.

**Comment by pasky** [comment]
(BTW you can also edit the system prompt in the buffer to modify it for a specific circumstance. I don't really do it myself, but it might be sometimes practical.)
