### ISSUE TITLE
disable default keymaps

### ISSUE THREAD

**Issue by chrisaq** [pasky/claude.vim#5]
It would be nice to be disable the default keymaps in case they are in conflict with other keymaps.

**Comment by felipejoribeiro** [comment]
Hi @chrisaq ! A new version (520c4fc0a1df269ad07560ff23bc4aa23cd43d0d) has ben released which adds user-defined mappings: https://github.com/pasky/claude.vim/pull/14

**Comment by pasky** [comment]
Yes, thanks @felipejoribeiro !
