### ISSUE TITLE
claude is rate limiting

### ISSUE THREAD

**Issue by kovetskiy** [pasky/claude.vim#6]
and the plugin is failing with error:
 Unknown Claude protocol output: "{"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}"

Context: I was doing chat and it was browsing files, just 3 files was enough.

**Comment by pasky** [comment]
But you can simply delte the error and retry (perhaps with smaller open files and after bumping yourself to tier 1), as the error is non-fatal, right?

We could certainly make the message slightly prettier, is there anything else you'd expect? (Besides Anthropic being saner about rate limits, having a 200k context window model and all.)
