### ISSUE TITLE
Can you please add better instructions for installing in NeoVim

### ISSUE THREAD

**Issue by codr1** [pasky/claude.vim#7]
Tried to install in NeoVim with Lazy package manager, but wasn't able to get it to work.  I added this to my plugins.lua config

```
 {
    "pasky/claude.vim",
    config = function()
      -- Configure claude.vim here
      vim.g.claude_api_key = <anthropic_key>
    end,
  },
```

`<leader>cc` and `<leader>ci` do not work.
Typing :ClaudeChat or :ClaudeInsert in normal mode do not work either...

(I am not an NeoVim expert by a very long shot, so I may be missing some very obvious things)

**Comment by pasky** [comment]
Hi, I'm not a big neovim user either, but the important thing here is that claude.vim is in vimscript rather than in lua.

I just have this in `init.lua`:
```
local vimrc = vim.fn.stdpath("config") .. "/vimrc.vim"
vim.cmd.source(vimrc)
```

**Comment by codr1** [comment]
Thanks, @pasky !  I will give it a try and if I am successful, I will try to make a video or some such.  Great job - really looking forward to trying it out.

**Comment by codr1** [comment]
Well, it was easier in the end.  Not sure why it didn't quite work the first time.  I swear I tried this before.  

In any case.  No need to mess with vimrc.   Just add the below to your plugin list, and it should work.   (The vim.keymap.set commands are optional, but the original keymaps conflict with NVChad existing keymaps, so they are somewhat specific to me.).  Also - this loads the key from an environment variable to somewhat improve secuirty.


```
{
  "pasky/claude.vim",
  lazy = false,
  config = function()
    -- Load API key from environment variable
    local api_key = os.getenv("ANTHROPIC_API_KEY")
    if api_key then
      vim.g.claude_api_key = api_key
    else
      vim.notify("ANTHROPIC_API_KEY environment variable is not set", vim.log.levels.WARN)
    end

    -- Add keymaps
    vim.keymap.set("v", "<leader>Ci", ":'<,'>ClaudeImplement ", { noremap = true, desc = "Claude Implement" })
    vim.keymap.set("n", "<leader>Cc", ":ClaudeChat<CR>", { noremap = true, silent = true, desc = "Claude Chat" })
  end,
},
