### ISSUE TITLE
free tier without api key possible?

### ISSUE THREAD

**Issue by laoshaw** [pasky/claude.vim#8]
can I use this in vim in free-tier before I buy the $20/m plan? do I need a api key for free tier?

**Comment by codr1** [comment]
It didn't work for me, but Anthropic is giving away $5 credit right now.  
Also - they work different from OpenAI.  While OpenAI has the $20 / month plan, Anthropic just charges you for usage.  You can buy a block of credits and you don't have to enable automatic top-up.  (this is accurate as of 21 Aug 2024)

**Comment by pasky** [comment]
Interesting, @codr1 how did it behave?

It should work in general (it did for me back in late June I think), just not while having large files open (b/c you hit the aggressive ratelimiting).

**Comment by codr1** [comment]
I haven't used it extensively in Vim.   I am stil in mess-with-neovim mode.  I plan to use it extensively next week and will let you know.
